name: Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Upload binaries to release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: sherlock
          target: ${{ matrix.target }}
          manifest-path: crates/sherlock/Cargo.toml
          include: LICENSE,README.md
          token: ${{ secrets.GITHUB_TOKEN }}
